### ISSUE TITLE
Events on local mount detected, but not from original OS (using SAMBA, in Cygwin)

### ISSUE THREAD

**Issue by ifoundthetao** [thekid/inotify-win#13]
My setup is that I'm using Cygwin.

I have a samba share set up, and I'm using inotifywait.exe to monitor file changes in a directory.  When I make the changes locally, they are noticed.  But when the changes occur from the machine that the share lives on, they aren't.

Here's what I'm using:
inotifywait -r -m -e modify Y:/location/to/share | while read line ; do echo "Notified!" ; done &

Again, this works as expected when I modify files on my machine, but when they are logged to on the host, I'm not notified.  

This could be a user error, too, As I'm also having issues watching specific files (it works with directories, but not individuals files), and using the cygwin-esque way of describing files (/cygdrive/y/location/to/share).

**Comment by thekid** [comment]
Can you check if #16 fixed this?

**Comment by thekid** [comment]
What I tested here looks good: I've started a Virtualbox instance and have mounted a path via network. I then monitor the directory using inotify-wait.exe from the host machine, and change the file system by sshing onto the guest:

![tests-with-vbox-and-mount](https://cloud.githubusercontent.com/assets/696742/5801011/3e60b864-9fe6-11e4-9f99-442503ead840.png)

**Comment by thekid** [comment]
Closing, please reopen if this continues to exist. PRs are, as always, welcome:)
