### ISSUE TITLE
Possibly wrong default filter

### ISSUE THREAD

**Issue by polkovnikov-ph** [thekid/inotify-win#17]
When creating a watcher

	new FileSystemWatcher {
		Path = path,
		IncludeSubdirectories = _recursive,
		Filter = "*.*"
	})

the filter supposes there's a dot in file name, but there could be no dot.

**Comment by thekid** [comment]
Good one! I guess `Filter=*` would do the trick, I'll test...

**Comment by thekid** [comment]
Nope, `*.*` also matches files without dot:

## Shell Window 1
```sh
$ echo "Test" > C:\Users\friebe\dir\file
```

## Shell Window 2
```sh
$ inotifywait.exe -m 'C:\Users\friebe\dir'
===> Monitoring for All in C:\Users\friebe\dir for create, modify, delete, move
```
C:\Users\friebe\dir MODIFY file
```
