### ISSUE TITLE
inotify-win doesn't stop after being executed without -m

### ISSUE THREAD

**Issue by androsland** [thekid/inotify-win#19]
I don't know if it is a featuer or a bug :smile: , but I have the following situation.
I run inotify-wait without the -m parameter and when i change a file, inotify-win captures the event successfully, but then, instead of exiting, it continues execution but fails to capture any more events.
Is this ok, or is something wrong?

**Comment by thekid** [comment]
You're right, this seems to have been introduced with some of the modifications between thekid/inotify-win@89b5ac3 and thekid/inotity-win@93171f8.

With an older binary it works as expected:

![quick 64](https://cloud.githubusercontent.com/assets/696742/8005275/7e7010b8-0b88-11e5-93f6-7e407e08a380.png)

I'll have a llook.

**Comment by thekid** [comment]
Yeah, I think [this here](https://github.com/thekid/inotify-win/commit/cf80b4d7ec5d7ea7c352e3ddb4a0c5ad3296d93f) is the cause.
