### ISSUE TITLE
Compiled version?

### ISSUE THREAD

**Issue by markaswift** [thekid/inotify-win#20]
Hi,

Is it possible to upload a compiled version to the repository? 

It would be a great help and I don't have the environment required to compile it... :-(

Thanks in advance,

Mark

**Comment by thekid** [comment]
You need .NET 4.x on your PC to run inotify-win, and if you have that, you also have the compiler for it, csc.exe

```sh
C:\Users\Timm>dir %WINDIR%\Microsoft.NET\Framework\|findstr v4
25.07.2015  19:57    <DIR>          v4.0.30319

C:\Users\Timm>dir %WINDIR%\Microsoft.NET\Framework\v4.0.30319\csc.exe
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 7058-0690

 Verzeichnis von C:\windows\Microsoft.NET\Framework\v4.0.30319

16.04.2014  01:34         1.853.072 csc.exe
               1 Datei(en),      1.853.072 Bytes
               0 Verzeichnis(se), 310.114.770.944 Bytes frei
```

See also #9

**Comment by warrenc5** [comment]
I'm an old man, so I wrote a quick reference list.

1. Those who write the code have the code,
2. those who have the code build the binaries,
3. those who build the binaries run the program,
4. those who run the program test the features,
5. those who test the features know how awesome those who wrote the code are.
