### ISSUE TITLE
Only last -e option takes effect

### ISSUE THREAD

**Issue by seanf** [thekid/inotify-win#23]
The Linux version of `inotifywait` supports multiple instances of the `-e` option, to listen for multiple event types. This version only seems to look at the last option. For example:

	$ inotifywait -e modify -e move -e create -e delete -e attrib -r .
	===> Watching for 0 in C:\example -r for attrib

	$ inotifywait -e modify -e move -e create -e delete -r .
	===> Watching for Deleted in C:\example -r for delete

	$ inotifywait -e modify -e move -e create  -r .
	===> Watching for Created in C:\example -r for create

	$ inotifywait -e modify -e move  -r .
	===> Watching for Renamed in C:\example -r for move

Also the "Watching for" messages seem to repeat themselves somewhat, like "Watching for **Created** in C:\example -r for **create**". 

Except for this odd message: "Watching for **0** in C:\example -r for attrib". I presume it is different because `attrib` is not supported on Windows.

**Comment by thekid** [comment]
Thanks, I'll have a look into this, should be easy enough to fix. If you come up with a pull request in the meantime, I'll accept and merge that, too.

**Comment by thekid** [comment]
Should be:

```sh
# By default, all events are watched
$ inotifywait .
===> Watching c:\tools\cygwin\home\Timm\devel\inotify-win for create, modify, delete, move

# A single event is specified
$ inotifywait -e create .
===> Watching c:\tools\cygwin\home\Timm\devel\inotify-win for create

# Multiple events are specified
$ inotifywait -e create -e delete .
===> Watching c:\tools\cygwin\home\Timm\devel\inotify-win for create, delete

# Multiple events are specified separated by commas
$ inotifywait -e create,delete .
===> Watching c:\tools\cygwin\home\Timm\devel\inotify-win for create, delete

# Events are distincted
$ inotifywait -e create,create .
===> Watching c:\tools\cygwin\home\Timm\devel\inotify-win for create

# Unknown events
$ notifywait -e attrib

Unbehandelte Ausnahme: System.ArgumentException: Unknown event name 'attrib'
```
