### ISSUE TITLE
inotifywait in background hang terminal

### ISSUE THREAD

**Issue by scim-dim-technique** [thekid/inotify-win#29]
When inotifywait is run un background the cygwin terminal hang

For exemple: `inotifywait -m d:  &`

After it was impossible to use the terminal until inotifywait was killed

**Comment by thekid** [comment]
Verified. This is because of how stopping the program works: Standard input is kept open by calling `Console.ReadLine()`, which of course captures input and thus makes the terminal unusable.

**Comment by thekid** [comment]
Help is welcome in form of pull requests!

**Comment by creallfluharty** [comment]
Sorry for butting in here, but I'm currently trying to work on a solution to #31 and was initially wondering if there was a general solution to both of these problems (ie, only `.Readline()` if STDIN is accessible to the process). In trying to find some way to check if the process is being run in the background, I found that there were some inconsistencies between what bash is supposed to do, and what was actually happening. Per the bash documentation:

> Only foreground processes are allowed to read from or, if the user so specifies with stty tostop, write to the terminal. Background processes which attempt to read from (write to when stty tostop is in effect) the terminal are sent a SIGTTIN (SIGTTOU) signal by the kernel’s terminal driver, which, unless caught, suspends the process.

[GNU Bash Manual - Job Control Basics][1]

So in theory, this shouldn't even be a problem (the process should be suspended when it tries to `ReadLine()`), but I'm not sure if the executable (which I assume is being compiled without anything like MinGW or Cygwin support) is even aware of or able to handle these signals.

I have no clue whether compiling C# with support for handing those signals is possible or not, and if it isn't then all of this information is basically useless except to say that bash background tasks are going to work weirdly.

[1]: https://www.gnu.org/software/bash/manual/html_node/Job-Control-Basics.html

**Comment by thekid** [comment]
@creallfluharty  - with your patch applied, it no longer hangs the terminal. However, once we foreground the process with `fg` inside a Cygwin bash, killing it via `Ctrl+C` no longer works, and I have to open another terminal and type `taskkill /im:inotifywait.exe /f` there to kill it. However, this re-renders the original terminal usable again. I'd say good enough 😇

**Comment by creallfluharty** [comment]
Although I can't say exactly why it doesn't handle `Ctrl+C` when it's brought to the foreground, from what I've gathered, Windows executables - even within Cygwin - can't really handle signals (such as SIGINT) unless they were compiled within Cygwin. I was trying to compile Mono for Cygwin to see if that might work, but it's been a painful rabbit hole so far, so I don't think I'm going to continue with that.

As annoying as it is, backgrounding/foregrounding tasks probably just isn't something that can work well with Windows executables unless they were somehow compiled with signal handling.
