### ISSUE TITLE
`inotifywait.exe` fails silently when STDIN is `NUL`

### ISSUE THREAD

**Issue by creallfluharty** [thekid/inotify-win#31]
When supplying `NUL` as STDIN to `inotifywait.exe` the program seems to crash without writing anything to STDERR or returning a non-zero exit code. This happens when running `inotifywait.exe` as a windowless subprocess (my use case) or in a service, as well as using redirection in the shell, like so:

```
C:\path\to\inotify>inotifywait.exe . < NUL

C:\path\to\inotify>echo %ERRORLEVEL%
0
```

PS: Thanks for maintaining this! It has been very useful so far!

Edit: Perhaps [this is intentional][1]?

[1]: https://github.com/thekid/inotify-win/blob/ff9501186a7380cd883063693098d1dc8147cd17/src/Runner.cs#L174

**Comment by thekid** [comment]
No, not intentional - instead, this is related to https://github.com/thekid/inotify-win/issues/29#issuecomment-517925406 and how waiting for all tasks to complete is hooked up to `Console.ReadLine()`. Pull requests are welcome!

**Comment by thekid** [comment]
> PS: Thanks for maintaining this! It has been very useful so far!

Thanks 🎉!

**Comment by creallfluharty** [comment]
I don't know any C# so please forgive my ignorance, but is that `Console.ReadLine()` code handling `Ctrl+Z`/EOF to allow for early termination? In that case, would handling `Ctrl+C` be a suitable alternative? (Or alternatively, allow `Ctrl+Z` whenever STDIN is available?) If so, I might be able to take a stab at a PR!

**Comment by thekid** [comment]
> ...is that Console.ReadLine() code handling Ctrl+Z/EOF to allow for early termination? 

It was introduced in PR #18
