### ISSUE TITLE
modify file will appear twice output events

### ISSUE THREAD

**Issue by Vzz1c** [thekid/inotify-win#35]
create , delete, move, there will be no problem, because I defined the cmd script, when the modification of the file will be executed twice script, which surprised me

**Comment by thekid** [comment]
This is explained [here](https://stackoverflow.com/a/1765094):

> You may notice in certain situations that a single creation event generates multiple Created events that are handled by your component. For example, if you use a FileSystemWatcher component to monitor the creation of new files in a directory, and then test it by using Notepad to create a file, you may see two Created events generated even though only a single file was created. This is because Notepad performs multiple file system actions during the writing process. Notepad writes to the disk in batches that create the content of the file and then the file attributes. Other applications may perform in the same manner. Because FileSystemWatcher monitors the operating system activities, all events that these applications fire will be picked up.

See also https://devblogs.microsoft.com/oldnewthing/20140507-00/?p=1053
