### ISSUE TITLE
Quoted paths

### ISSUE THREAD

**Issue by pasha-zzz** [thekid/inotify-win#37]
1) inotifywait C:\\
`===> Watching C:\*.* for create, modify, delete, move`

2) inotifywait "C:\\"
Black screen, no output, hangs

3) inotifywait C:\\Test
`===> Watching C:\Test*.* for create, modify, delete, move`
(works fine, cosmetic - no backslash delimiting path from wildcard)

4) inotifywait "C:\\Test"
all OK like in 3)

5) inotifywait "C:\\Test\\"
like in 2) not working

6) inotifywait "C:\\Test\\."
all OK like in 3) and 4)

Results like 2) and 5) we can get if pass any not existing path. And even if we create this path later program still hangs.

**Comment by thekid** [comment]
> inotifywait "C:\"
> Black screen, no output, hangs

You have successfully escaped the trailing double quote, thus telling your shell not to treat it as the end of the string it's enclosing, but as a literal double quote. You can see the same behavior when you write `echo "C:\"`. See e.g. https://bash.cyberciti.biz/guide/Quoting

**Comment by thekid** [comment]
To produce a better error message, we could add the following:

```diff
❯ git diff
diff --git a/src/ArgumentParser.cs b/src/ArgumentParser.cs
index e31d382..c3cd984 100755
--- a/src/ArgumentParser.cs
+++ b/src/ArgumentParser.cs
@@ -95,6 +95,8 @@ namespace De.Thekid.INotify
             {
                 result.Paths.Add(System.IO.Path.GetFullPath(option));
             }
+
+            throw new ArgumentException(string.Format("Path does not exist: `{0}`", option));
         }

         /// Creates a new argument parser and parses the arguments
```

**Comment by thekid** [comment]
![image](https://user-images.githubusercontent.com/696742/235790745-e0f31c90-f03c-4ac2-8c04-4ba9e638475c.png)

**Comment by pasha-zzz** [comment]
> If in cmd.exe: Same

No. In cmd.exe backslash isnt escaping character. `^` is escaping char

**Comment by thekid** [comment]
You can clearly see that the string `C:"` _including a trailing double quote_ ends up in the `option` variable, which is initialized from the command line arguments passed to the code. This is just how the constellation of Windows cmd.exe plus a Windows executable works, there's nothing special I'm doing here.

**Comment by lvmm** [comment]
I am afraid inotifywait is surprisingly unique in its approach to quoting - this is ls from cygwin run from cmd prompt
```
C:\temp>ls -ld "c:\temp"
drwxr-xr-x 1 xxx Domain Users 0 Mar 25 09:23 'c:\temp'
```

**Comment by thekid** [comment]
Again, inotify is not doing any special here, see how the trailing backquote gets passed in the following example:

```cmd
C:\Tools\Cygwin\home\timmf\devel\inotify-win>type Args.cs
using System;

class Args
{
    public static void Main(string[] args)
    {
        Console.WriteLine("Given argument: [{0}]", args[0]);
    }
}
C:\Tools\Cygwin\home\timmf\devel\inotify-win>csc /out:Args.exe Args.cs

C:\Tools\Cygwin\home\timmf\devel\inotify-win>Args.exe "C:\"
Given argument: [C:"]

C:\Tools\Cygwin\home\timmf\devel\inotify-win>Args.exe "C:\temp"
Given argument: [C:\temp]

C:\Tools\Cygwin\home\timmf\devel\inotify-win>Args.exe "C:\temp\"
Given argument: [C:\temp"]
```

**Comment by lvmm** [comment]
And of course it's not the first time this bug has been encountered, e.g. https://www.mobzystems.com/code/bugingetcommandlineargs/
