### ISSUE TITLE
--include regex option

### ISSUE THREAD

**Issue by pasha-zzz** [thekid/inotify-win#38]
In Linux version since 3.20.1. Can be added to windows ver?

P.S.: And --includei too...

**Comment by thekid** [comment]
Have a look at #39, check out the branch, compile and test it. Does it work for you?

**Comment by pasha-zzz** [comment]
All works fine! Thanks!
To the compilation command add /o for optimization.

**Comment by thekid** [comment]
> To the compilation command add /o for optimization.

Done in 33edb6f
