### ISSUE TITLE
Wrong Result

### ISSUE THREAD

**Issue by xpresso** [thekid/inotify-win#7]
> inotifywait -e create,delete,modify,move -mrq C:\Test

When moving C:\Test\TestFolder1\testfile.txt to C:\Test\TestFolder2\
It results in c:\Test DELETE TestFolder1\testfile.txt which is wrong,
should be

c:\Test MOVED_FROM TestFolder1\testfile.txt
c:\Test MOVED_TO TestFolder2\testfile.txt

**Comment by thekid** [comment]
This might have been caused by some events being swallowed. Initial tests suggest this have been fixed:
![issue-7](https://cloud.githubusercontent.com/assets/696742/5801076/3cde6d00-9fe7-11e4-82ad-2e2f009fc4f8.png)

**Comment by IbnSaeed** [comment]
any update ?

**Comment by thekid** [comment]
Sorry, no. This goes over my C# / Windows programming skills (how can I find out `testfile.txt` *was* the same file as something deleted when examining the CREATE event? - is this even possible?), which is why I'm open to accept any pull requests.

**Comment by IbnSaeed** [comment]
Alright, thanks.

**Comment by blaggacao** [comment]
I would suggest comparing the hashed values. (The technique used in web frameworks to invalidate a cached file, if there has been a minor change by altering the filname, wich contains a hash value.)

I think, knowing C#, which I don't ist's pretty straight forward.

Here is the relevenat part copied from [stackoverflow](http://stackoverflow.com/questions/16318087/calculate-the-hash-of-the-contents-of-a-file-in-c):


You could use `MD5CryptoServiceProvider`, which will work with text based files as well as binary files.
```
byte[] myFileData = File.ReadAllBytes(myFileName);
byte[] myHash = MD5.Create().ComputeHash(myFileData);
```
Or... if you work with large files and do not want to load the whole file into memory:
```
byte[] myFileData;
using (var md5 = MD5.Create())
using (var stream = File.OpenRead(myFileName))
    myFileData = md5.ComputeHash(stream);
```
You can compare to byte arrays from two files with `Enumerable.SequenceEqual`:
```
myHash1.SequenceEqual(myHash2); 
```

**Comment by thekid** [comment]
> byte[] myFileData = File.ReadAllBytes(myFileName);

Yes, I'd been thinking about this too. On the downside, this could be quite an issue for a 2 Gigabyte file on a Network drive... but even for smaller checkouts around 10 - 50 Megabytes but say with frequent changes this could be quite a performance hit.

> BTW, thanks for the good work!

You're welcome!

**Comment by thekid** [comment]
For the usecase you're thinking about I think keeping the intelligence about replicating the changes in rsync is sufficient, and just using this tool to detect **that** there have been changes.

**Comment by blaggacao** [comment]
I was about to say, the -c command of rsync does checksum, but not by default, as it is slow as you suggested... I'm working on a shellscript to do exactly what you suggest, leaving apart the moving case, as for development in case of reordering the file structure a need restarting the server is not that far fetched.

**Comment by raffaelemancuso** [comment]
@thekid Hello, is this resolved? Because it is closed but the README talks about it as if it is still an issue

**Comment by thekid** [comment]
The note in the README (*When moving files, not all events are reported consistently with the original*) is still correct. This issue is closed as the fact that how the underlying events are triggered is just how Windows filesystem APIs work there is no performant way to make this compatible with the `inotify` original, which relies on how Linux filesystem APIs work.
